version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    volumes:
      - /mnt/musicdrive/music:/music
      - /mnt/musicdrive/navidrome-data:/data
    environment:
      # Optional: Set these environment variables for better performance
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
    restart: unless-stopped 